### ISSUE TITLE
Add regression test suite

### ISSUE THREAD

**Issue by PrashantG** [IEEEICSG/IEEE_Taggant_System#3]
Introduce a regression test suite and scripts to run the tests automatically for all parts of the project:

1. Taggant Library (Windows platform to start with then improve support for other platforms)
2. SSV Test
3. UPX

This is to test and have certain degree of confidence before committing any changes. Also this would allow special cases, conditions and samples to be added and functionality against these maintained over time.

**Comment by peterferrie** [comment]
created testharness source and test-set description
