### ISSUE TITLE
Potential double free issue in timestamp.c

### ISSUE THREAD

**Issue by noobpwnftw** [IEEEICSG/IEEE_Taggant_System#8]
After inspecting a crash case during taggant creation, I suspect that this probably the cause:

In timpstamp.c line 270:
memory_free(resultBuffer);

Here the memory of the pointer "resultBuffer" is freed but the pointer is not set to NULL, if anything happens in the second iteration, i.e. the "http_read" function failed due to some error, this memory pointer is freed again in line 334 which will cause a crash.

**Comment by peterferrie** [comment]
> After inspecting a crash case during taggant creation, I suspect that this
> probably the cause:
>
> In timpstamp.c line 270:
> memory_free(resultBuffer);

Thank you for the report.  I see the same issue.  I will get that fixed.

**Comment by peterferrie** [comment]
fixed in 65755d0220446ab5840803e5b4fc461e0fa91d98
